[package]
edition = "2021"
name = "platform_napi"
version = "0.0.0"

[lib]
crate-type = [ "cdylib" ]

[profile.release]
lto = true
strip = true

[dependencies]
napi = { version = "2.16.13", features = [ "napi8" ] }
napi-derive = "2.16.12"

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.58.0"
features = [
  "Win32_Foundation",
  "Win32_System_Shutdown",
  "Win32_System_Threading",
  "Win32_UI_WindowsAndMessaging",
]

[build-dependencies]
napi-build = "2.1.3"
