/* tslint:disable */

/* auto-generated by NAPI-RS */

export declare function setMainWindowHandle(bigint: bigint): void
export declare function insertWndProcHook(callback: (...args: any[]) => any): void
export declare function removeWndProcHook(): boolean
export declare function acquireShutdownBlock(reason: string): boolean
export declare function releaseShutdownBlock(): boolean
